### PR TITLE
Add functions for the PR demo (08-16-1996)

### PR DESCRIPTION
**Pull request by ghost**
This thing was tedious due to the countless differences in the demo vs. beta and beyond. Interestingly enough though is that they didn't exclude any code from the demo like they did in the battle.net beta. This was probably because someone unlocked the demo so they made sure to remove the code altogether in the beta. Only a handful of files have different names, and the linking order is about the same as the 1.00 debug. In particular, notice the following code:

`multi.cpp` -> uses DirectPlay for multiplayer instead of Storm, very early in the works
`diablo/init.cpp` -> there is no `DiabloUI`, instead the title screen is handled with custom code
`drlg_l1.cpp` -> contains dungeon algorithms for both level type one and five.

The latter is the one we see in the retail version of the game, but the other one is the maze-like one found in early magazine screenshots. This is why many functions are called `CreateL5Dungone`, `L5GChamber`, etc. because there were originally two algorithms using the same tile set.

That's about it, I figured out most of the structs too after a fair bit of work. We now have documentation for various unused structs and fields that existed in 1.09, such as the unused missile struct.

### CODE REVIEW

**Comment by sskras** [comment]
A massive digi-archeological bunch !  Wow.

**Comment by mewmew** [comment]
> That's about it, I figured out most of the structs too after a fair bit of work. We now have documentation for various unused structs and fields that existed in 1.09, such as the unused missile struct.

That's really great! Wow, @galaxyhaxz you continue to amaze.

**Comment by ghost** [comment]
For those of you interested, you can do a few edits to the demo to load the unused dungeon algorithm. However it is really buggy and crashes a lot. I was able to decompile and port it to devilution where it runs perfectly. Below are a few screenshots of it in action. Anyone who has seen the old February-May 1996 screenshots will be familiar with these. (lighting removed for clarity)

Coffin room, notice all the extra walls.
coffins

Old version of the butcher. Notice the painting on the wall and the coffins that aren't in the final game.
butcher

Last but not least, the mysterious room which appeared in the very first screenshot ever released of diablo. No one really knows what it did, but hey, we now have the source code to the original algorithms to spawn it properly in Devilution :wink: 
mystery

**Comment by mewmew** [comment]
> For those of you interested, you can do a few edits to the demo to load the unused dungeon algorithm. However it is really buggy and crashes a lot. I was able to decompile and port it to devilution where it runs perfectly. Below are a few screenshots of it in action. Anyone who has seen the old February-May 1996 screenshots will be familiar with these. (lighting removed for clarity)

Wow!! That gave me the shills. So cool!

**Comment by mewmew** [comment]
From alpha 3 (ref: http://diablo-evolution.net):

Alpha 3

**Pull request merged**
