### PR TITLE
Add addresses of functions in debug release

### PR DESCRIPTION
**Pull request by mewmew**
- [x] APPFAT.CPP
- [x] AUTOMAP.CPP
- [x] CAPTURE.CPP
- [x] CODEC.CPP
- [x] CONTROL.CPP
- [x] CURSOR.CPP
- [x] DEAD.CPP
- [x] DEBUG.CPP
- [x] DIABLO.CPP
- [x] DOOM.CPP
- [x] DRLG_L1.CPP
- [x] DRLG_L2.CPP
- [x] DRLG_L3.CPP
- [x] DRLG_L4.CPP
- [x] DTHREAD.CPP
- [x] DX.CPP
- [x] EFFECTS.CPP
- [x] ENCRYPT.CPP
- [x] ENGINE.CPP
- [x] ERROR.CPP
- [ ] FAULT.CPP
- [x] GAMEMENU.CPP
- [x] GENDUNG.CPP
- [x] GMENU.CPP
- [x] HELP.CPP
- [x] INIT.CPP
- [x] INTERFAC.CPP
- [x] INV.CPP
- [x] ITEMS.CPP
- [x] LIGHTING.CPP
- [x] LOADSAVE.CPP
- [x] MAINMENU.CPP
- [x] MINITEXT.CPP
- [x] MISSILES.CPP
- [x] MONSTER.CPP
- [x] MOVIE.CPP
- [x] MPQAPI.CPP
- [x] MSG.CPP
- [x] MULTI.CPP
- [x] NTHREAD.CPP
- [x] OBJECTS.CPP
- [x] PACK.CPP
- [x] PALETTE.CPP
- [x] PATH.CPP
- [x] PFILE.CPP
- [x] PLAYER.CPP
- [x] PLRMSG.CPP
- [x] PORTAL.CPP
- [x] QUESTS.CPP
- [x] SCROLLRT.CPP
- [x] SETMAPS.CPP
- [x] SHA.CPP
- [x] SOUND.CPP
- [x] SPELLS.CPP
- [x] STORES.CPP
- [x] SYNC.CPP
- [x] THEMES.CPP
- [x] TMSG.CPP
- [x] TOWN.CPP
- [x] TOWNERS.CPP
- [x] TRACK.CPP
- [x] TRIGS.CPP
- [x] WAVE.CPP
- [x] RENDER.CPP

### CODE REVIEW

**Comment by mewmew** [comment]
@galaxyhaxz Lets keep this PR open until all functions of the debug release have been referenced.

**Comment by mewmew** [comment]
Note, which looking at `control.cpp` I noticed a typo for v1.09b.

It was written as:

| Diablo | CONTROL.CPP |
|-----|-----|
| N/A | j_ClearPanel |
| 4042C5 | InitPanelStr |

It should be written as:

| Diablo | CONTROL.CPP |
|-----|-----|
| 4042C5 | j_ClearPanel |
| N/A | InitPanelStr |

as indicated by the following listing from IDA:

```asm
.text:004042C5 ; void __cdecl j_control_ClearPanel()
.text:004042C5 j_control_ClearPanel proc near
.text:004042C5                 jmp     control_ClearPanel
.text:004042C5 j_control_ClearPanel endp               ;
```

**Edit:** fixed in commit https://github.com/diasurgical/scalpel/pull/7/commits/fa569cfdf9af0749e20ba6f24f6f10bb3959c622

**Comment by ghost** [comment]
@mewmew Good catch on that typo! Picking apart the debug release will help us untangle some messy code and maybe even add the assert strings. I'll help you if there's some free time this weekend. Thankfully the debug, beta, and 1.00 all seem to be linked the same.

**Comment by mewmew** [comment]
> @mewmew Good catch on that typo! Picking apart the debug release will help us untangle some messy code and maybe even add the assert strings. I'll help you if there's some free time this weekend. Thankfully the debug, beta, and 1.00 all seem to be linked the same.

If you want, you could start from the bottom, and I'll continue going from the top (of the list posted in https://github.com/diasurgical/scalpel/pull/7#issue-205447024).

**Comment by mewmew** [comment]
In commit https://github.com/diasurgical/scalpel/pull/7/commits/a81634719ad4ab20dc431a0f25cb9773f0269113 `world.cpp` was renamed to `render.cpp`. Just as a heads up.

**Comment by ghost** [comment]
Added 12 more files. I'm starting from the first address (0x401000) and working downwards.

> In commit a816347 world.cpp was renamed to render.cpp. Just as a heads up.

I'll update the main repo to reflect this. A little more speculation: perhaps the reason this file was linked last was that it was actually called `render.asm/render.s` seeing as it was written mostly in assembly. In Hellfire they may have changed it to `.cpp` so it linked alphabetically. Just a thought :)

**Comment by mewmew** [comment]
> Added 12 more files. I'm starting from the first address (0x401000) and working downwards.

That's great! Haha, couldn't wait until weekend? :)

> I'll update the main repo to reflect this. A little more speculation: perhaps the reason this file was linked last was that it was actually called render.asm/render.s seeing as it was written mostly in assembly. In Hellfire they may have changed it to .cpp so it linked alphabetically. Just a thought :)

It does sound plausible, especially since Brevik mentioned assembly being used in the postmortem.

**Comment by mewmew** [comment]
@galaxyhaxz From what I can tell, the first two functions of `appfat.cpp` actually belong to `fault.cpp`.

```py
MakeNameEx(LocByName("sub_40C363"), "break_exception", SN_NOWARN)
MakeNameEx(LocByName("sub_40C38B"), "break_filter", SN_NOWARN)
```

The first function `40C363`, was broken into two functions in 1.09b, namely `exception_set_filter` (`41883C`) and `exception_set_filter_ptr` (`418853`).

The second function `40C38B` looks to be an earlier version of `TopLevelExceptionFilter` (`4182D7`).

**Comment by ghost** [comment]
> That's great! Haha, couldn't wait until weekend? :)

No I was too excited, wanted to do this for awhile. Added another 20 files =D

> From what I can tell, the first two functions of appfat.cpp actually belong to fault.cpp

Actually, those functions are unique to the debug release. They are used in `nthread.cpp`:
```
bool nthread_debug_keypress(int VKEY)
    if ( v1 == (void *)3 )                      // Ctrl + C
    {
        if ( !exclusive )
        {
            break_exception();
            drawpanflag = 255;
        }
    }
```
There are three more debug controls in the function `nthread_debug_keypress` that we didn't know about before, they only work in multiplayer:
- `Ctrl + C` calls `break_exception` and triggers an `INT3` breakpoint
- `Ctrl + S` pauses the current screen frame`
- `Ctrl + P` displays number of mouse clicks by each player and the frame counter

**Comment by mewmew** [comment]
> There are three more debug controls in the function nthread_debug_keypress that we didn't know about before, they only work in multiplayer:

That's way cool :) Good find!

**Comment by mewmew** [comment]
> No I was too excited, wanted to do this for awhile. Added another 20 files =D

Haha, yes. We were both so excited that we worked on the same file. I also added mpqapi.cpp just now. Had a minor collision, so resolved it.

Most notably, `4172DC` is a function unique to the debug release (`mpqapi_is_save_modified`), and not the `mpqapi_store_creation_time` function, even if it would seem so at first glance based on linking order.

Some docs for the new functions:

```c
// mpqapi_is_save_modified reports whether the given multiplayer save file has been modified.
bool __fastcall mpqapi_is_save_modified(char *pszArchive, DWORD dwChar);

// mpqapi_time_before reports whether the time instant t1 is before or equal to t2.
bool __fastcall mpqapi_time_before(FILETIME *t1, FILETIME *t2);

// mpqapi_update_multi_creation_time updates the creation time of the save file for the given multiplayer character.
void __fastcall mpqapi_update_multi_creation_time(DWORD dwChar);
```

I've added some files to the scalpel.xls file. As it's a binary file though, we cannot work as easily on that at the same time. Gotta love git merge for text files though!

**Comment by ghost** [comment]
> Most notably, 4172DC is a function unique to the debug release (mpqapi_is_save_modified), and not the mpqapi_store_creation_time function, even if it would seem so at first glance based on linking order.

Yeah there were two functions i just slapped a `_0` onto so we could figure out what they did later. Glad you're already one step ahead :D

**Comment by mewmew** [comment]
@galaxyhaxz I made a few minor updates to scalpel.xls and related scripts.

* Rename `portals.cpp` to `portal.cpp`, as based on the follow assert string from the debug release:

**Note**: it was correct in the Files tab of the spread sheet, the update was made in the Functions tab

```
.data:004C5D78	0000001C	C	C:\\Diablo\\Direct\\portal.cpp
```

---

* Rename `diablo_find_window` to `diablo_focus_window`, to closer match its effect. Also, the return type is updated from `HWND` to `bool`.

---

* Rename `diablo_hotkey_msg` to `NetMsg`, as based on the app name parameter of the call to `GetPrivateProfileStringA`.

```c
    GetPrivateProfileStringA("NetMsg", net_msg_hotkeys[net_msg_id_W], net_msg_texts[net_msg_id_W], text, 80u, filename);
```

---

* Rename `diablo_pause_game` to `diablo_toggle_pause`, to closer match its effect.

---

**Comment by mewmew** [comment]
I also added a Data tab in `scalpel.xls` so we can start tracking global variables when we feel like it.

In the Functions tab, I added a *Certainty* column and a *Notes* column, so that we can track what function names are indeed identical to the release versions of Diablo, and where that certainty comes from (e.g. assert strings, SYM info, etc.) We can remove these two columns at a later stage, but for now it helps to track what is *for sure* complete, and what is *best effort guesses*.

**Comment by ghost** [comment]
> Note: it was correct in the Files tab of the spread sheet, the update was made in the Functions tab

I call lack of sleep :stuck_out_tongue: 

> In the Functions tab, I added a Certainty column and a Notes column, so that we can track what function names are indeed identical to the release versions of Diablo, and where that certainty comes from (e.g. assert strings, SYM info, etc.) We can remove these two columns at a later stage, but for now it helps to track what is for sure complete, and what is best effort guesses.

Good idea! I had thought about doing this originally but took the lazy route. In most cases we can put either "Assert" or "Symbol" in that column to keep things simple. 85% of the names or so are based on the PSX, 5% based on assert strings and 10% are guessed.

We can also add notes next to the file names as well, so we know if they are correct. Some of the file names (`fault.cpp`, `logging.cpp`) are based on Diablo 2 assert strings for example.

**Comment by mewmew** [comment]
> We can also add notes next to the file names as well, so we know if they are correct. Some of the file names (fault.cpp, logging.cpp) are based on Diablo 2 assert strings for example.

That would be great.

@galaxyhaxz How would you like to do for handling the xls file in the future? Seeing as it's a binary file and we can't edit it at the same time. Just don't want to end up in the situation where we both work on it and later have to throw away work, as that can be very demotivational. @7i and I had to do that a few years back when playing with the IDB databases, and it took away a lot of the fun.

**Comment by mewmew** [comment]
> Good idea! I had thought about doing this originally but took the lazy route. In most cases we can put either "Assert" or "Symbol" in that column to keep things simple. 85% of the names or so are based on the PSX, 5% based on assert strings and 10% are guessed.

Updated in rev https://github.com/diasurgical/scalpel/pull/7/commits/585edeb7255a891fe235b0788128e582027d57f8, we're now using `assert`, `psx` and `guess` in the Certainty column to track how we inferred the name.

**Edit:** For assert, currently information is included from calls to `appfat_assertion_failed` and `TermMsg`.

**Comment by ghost** [comment]
> How would you like to do for handling the xls file in the future?

@mewmew Well I thought about using tabbed text originally, which would allow easier editing and it uses non-proprietary format. The only problem is that it's more difficult to read without formatting and each time you load it you have to manually enter in everything so it uses the right settings (fixed width font, text-formatted cels, tabs, etc.). But perhaps it wouldn't be as bad in Notepad++. What tools on Linux are viable for tab-text files?

**Comment by mewmew** [comment]
> But perhaps it wouldn't be as bad in Notepad++. What tools on Linux are viable for tab-text files?

I tried converting the xls to a csv file using tab delimiters, however, loading this file back into LibreOffice Calc (and manually clicking the options you mentioned), the result looks quite terrible in comparison.

2018-08-05-215937_1024x743_scrot

Lets perhaps keep it in xls format for now? At least until we figure out a good representation. In the end, I'd prefer that this information ended up in an open file format, so that we can easily create tools to consume the data. Perhaps CVS will be the end format, but we use XLS while editing; and try to communicate before doing any large edits, so that we don't have to duplicate work on this file.

**Comment by mewmew** [comment]
Just as a heads up, two functions were renamed based on assert information from the debug release.

* Rename `dx_lock_mutex` to `lock_buf_priv`
* Rename `TermDlg` to `ErrDlg`

**Comment by ghost** [comment]
> and try to communicate before doing any large edits, so that we don't have to duplicate work on this file.

Yeah that's why I'm just updating the script right now until this PR is complete. So I'm thinking space-formatted text might be a good idea. https://pastebin.com/DHfLjnLG

That doesn't look too bad does it? Even though there's no formatting, you can edit it with just about anything. If you use Spreadsheet software, you can punch in `10` for space-delimited text and use fixed-width.
image

**Comment by mewmew** [comment]
I tried opening https://pastebin.com/raw/DHfLjnLG with LibreOffice, using fixed width 10. It kind of works but doesn't look great. Although I agree that the plain text representation of it turned out quite clean, so I would probably edit it using Sublime Text or some other editor. My main concern is to be able to access the data from a tool in a simple and unambiguous way later on. With fixed width encoding it seems you'd have to configure a bit, whereas using say tab separated values may work without any configuration of a library. I imagine we could also play around with using tabs instead of spaces and then set the display width of tabs to 10 to get it to represent well in plain text.

2018-08-06-110616_959x718_scrot

**Comment by ghost** [comment]
A few of the "guessed" names are actually correct as per the PSX. It appears you are referencing from the Japanese release? The beta contains these functions which are not in the Japanese:
```
03f027: $800783a0 94 Def class EXT type FCN UCHAR size 0 name M_Ranged__Fi
12a627: $80153630 94 Def class EXT type FCN VOID size 0 name M_StartWalk__Fiiiiii
12a4f4: $8015258c 94 Def class EXT type FCN UCHAR size 0 name PosOkMonst2__Fiii
```

**Comment by mewmew** [comment]
> A few of the "guessed" names are actually correct as per the PSX. It appears you are referencing from the Japanese release? The beta contains these functions which are not in the Japanese:

Oh, that's great! I did indeed look at the Japanese release. Besides the beta, have you managed to come across any older releases or anything else we could dig into for symbol information and the like?

**Edit:** fixed in rev https://github.com/diasurgical/scalpel/pull/7/commits/313bd666c12582dd71943823410619a47f1d4e27

**Comment by ghost** [comment]
> Oh, that's great! I did indeed look at the Japanese release. Besides the beta, have you managed to come across any older releases or anything else we could dig into for symbol information and the like?

Unfortunately not. We have the Beta/Japanese PSX and the 1.00 debug and that's pretty much it. The PC beta only contains a handful of file name asserts and the pre-release demo contains almost no strings altogether. Interestingly though the demo has different file names (`snd.cpp`, `winapp.cpp`, `wave2.cpp`, `MoPaQ.cpp`).

So check this out: https://assemblergames.com/threads/off-req-diablo-1-source-code-for-psx-beta-builds.69424/

Apparently one of those members owns an entire set of PSX development discs which undoubtedly will have symbol files. It could really help us to get as many revisions as possible, especially older than the `Easy as Pie` which might even contain symbols for the original `engine.cpp/render.cpp` and possibly other removed code. Sadly it doesn't appear they want to share anything though, perhaps they'd be more open if I could get in touch.

By the way, I found `COUNT OF MONTE ARSEHOLE` and other names Climax used pretty funny :D

**Comment by mewmew** [comment]
> Apparently one of those members owns an entire set of PSX development discs which undoubtedly will have symbol files. It could really help us to get as many revisions as possible, especially older than the Easy as Pie which might even contain symbols for the original engine.cpp/render.cpp and possibly other removed code. Sadly it doesn't appear they want to share anything though, perhaps they'd be more open if I could get in touch.

Please do. I'd recommend sending an email, and initially asking for something smaller, e.g. the SYM file of older releases, nothing else. Then they may be more willing to help.

Basically, they want to keep their release rare, and I guess they stop being rare if you have a dump floating around.

Let me know how it goes.

**Comment by ghost** [comment]
@mewmew All finished :) There wasn't a fault.cpp however, but there are a few functions part of diablo.cpp and engine.cpp that seem to work similar.

**Comment by mewmew** [comment]
This branch is further along then master, as it adds the addresses of the debug release. I checked the diff and where function names differ, this one has the *new* name.

Besides the added addresses for the debug release, this is the diff of `scalpel.xls`:

```diff
--- old.txt	2018-12-26 23:35:51.433889211 +0100
+++ new.txt	2018-12-26 23:34:10.906630091 +0100
@@ -16,7 +16,7 @@
 | 411932 | 401A88 | 401A65 | DDErrDlg |
 | 41197A | 401AAB | 401A88 | DSErrDlg |
 | N/A | 401ACE | 401AAB | CenterDlg |
-| N/A | 401B60 | 401B3D | TermDlg |
+| N/A | 401B60 | 401B3D | ErrDlg |
 | N/A | 401BED | 401BCA | FuncDlg |
 | N/A | 401C32 | 401C0F | TextDlg |
 | N/A | N/A | 401C2E | ErrDlg |
@@ -70,8 +70,8 @@
 | 415BA4 | 40454A | 404218 | AddPanelString |
 | 415BFA | 40457C | 40424A | ClearPanel |
 | 415C1E | 40458B | 404259 | DrawPanelBox |
-| 415CA7 | 4045F7 | N/A | j_ClearPanel |
-| N/A | N/A | 4042C5 | InitPanelStr |
+| 415CA7 | 4045F7 | 4042C5 | j_ClearPanel |
+| N/A | N/A | N/A | InitPanelStr |
 | 415CBC | 4045FC | 4042CA | SetFlaskHeight |
 | 415D26 | 40464D | 40431B | DrawFlask |
 | 415D76 | 40468D | 40435B | DrawLifeFlask |
@@ -156,6 +156,7 @@
 | Beta | Hellfire | Diablo | DIABLO.CPP |
 | N/A | N/A | 4087B1 | j_diablo_cpp_init |
 | N/A | N/A | 4087B6 | diablo_cpp_init |
+| N/A | N/A | N/A | diablo_clear_key_and_mouse_events |
 | 490C20 | 408EE9 | 4087C1 | FreeGameMem |
 | 490F61 | 408F61 | 408838 | diablo_init_menu |
 | 490CE9 | 409015 | 4088E2 | run_game_loop |
@@ -166,7 +167,8 @@
 | N/A | 4093F9 | 408CB1 | diablo_parse_flags |
 | 4910C8 | 4095FC | 408D61 | diablo_init_screen |
 | N/A | 40964C | N/A | diablo_TopLevelExceptionFilter |
-| N/A | 40966E | 408DB1 | diablo_find_window |
+| N/A | N/A | N/A | diablo_exception_handler |
+| N/A | 40966E | 408DB1 | diablo_focus_window |
 | N/A | 4096B1 | 408DF4 | diablo_reload_process |
 | N/A | 4098C2 | 408FCF | PressEscKey |
 | N/A | 409951 | 40905E | DisableInputWndProc |
@@ -179,10 +181,10 @@
 | 49200C | 40A3F6 | N/A | diablo_49200C |
 | N/A | N/A | 409A89 | j_gmenu_run_item |
 | 492045 | 40A3FB | 409A8E | PressSysKey |
-| 49208F | 40A41D | 409AB0 | diablo_hotkey_msg |
+| 49208F | 40A41D | 409AB0 | NetMsg |
 | 4921E7 | 40A4BE | 409B51 | ReleaseKey |
 | 49220C | 40A4C9 | 409B5C | PressKey |
-| N/A | 40A8FC | 409F43 | diablo_pause_game |
+| N/A | 40A8FC | 409F43 | diablo_toggle_pause |
 | 492954 | 40A938 | 409F7F | PressChar |
 | 4931A7 | 40AE68 | 40A391 | LoadLvlGFX |
 | 493377 | 40B02D | 40A4B4 | LoadAllGFX |
@@ -390,7 +392,7 @@
 | N/A | 417F59 | 4155C2 | dx_create_primary_surface |
 | N/A | 417FB1 | 41561A | dx_DirectDrawCreate |
 | N/A | 41802C | 415695 | j_dx_lock_mutex |
-| N/A | 418031 | 41569A | dx_lock_mutex |
+| N/A | 418031 | 41569A | lock_buf_priv |
 | N/A | 4180BE | 415720 | j_dx_unlock_mutex |
 | N/A | 4180C3 | 415725 | dx_unlock_mutex |
 | N/A | 41813E | 4157A0 | dx_cleanup |
@@ -548,7 +550,7 @@
 | 412380 | 41BDFB | 41930B | SetDungeonMicros |
 | 412564 | 41BF44 | 41944A | DRLG_InitTrans |
 | 4125A3 | 41BF74 | 419477 | DRLG_MRectTrans |
-| 41264A | N/A | N/A | gendung_41264A |
+| 41264A | N/A | N/A | gendung_copy_transparency |
 | 41273D | 41BFCD | 4194D0 | DRLG_RectTrans |
 | 4127B8 | 41C012 | 419515 | DRLG_CopyTrans |
 | 412801 | 41C031 | 419534 | DRLG_ListTrans |
@@ -556,6 +558,7 @@
 | N/A | 41C0A3 | 4195A2 | DRLG_InitSetPC |
 | 412911 | 41C0BA | 4195B9 | DRLG_SetPC |
 | N/A | 41C10E | 41960C | Make_SetPC |
+| N/A | N/A | N/A | gendung_40DDA5 |
 | N/A | 41C15D | 41965B | DRLG_WillThemeRoomFit |
 | N/A | 41C2F9 | 4197F4 | DRLG_CreateThemeRoom |
 | N/A | 41C708 | 419C10 | DRLG_PlaceThemeRooms |
@@ -1100,7 +1103,7 @@
 | N/A | N/A | 430FDF | j_monster_cpp_init |
 | N/A | N/A | 430FE4 | monster_cpp_init |
 | 401000 | 43B0CB | 430FEF | InitMonsterTRN |
-| 40110B | N/A | N/A | monster_40110B |
+| 40110B | N/A | N/A | monster_is_anim_loaded |
 | 40120F | 43A905 | 43107B | InitLevelMonsters |
 | 4012C4 | 43A95E | 4310CF | AddMonsterType |
 | 4013CE | 43A9DB | 43114F | GetLevelMTypes |
@@ -1184,7 +1187,7 @@
 | N/A | 43FABB | 435F35 | M_CallWalk2 |
 | N/A | 43FB44 | 435FBA | M_DumbWalk |
 | 409939 | 43FB65 | 435FDB | M_RoundWalk |
-| 409ACC | N/A | N/A | monster_409ACC |
+| 409ACC | N/A | N/A | M_Face |
 | 409B93 | 43FC36 | 4360B1 | MAI_Zombie |
 | 409DFA | 43FDF5 | 4361F7 | MAI_SkelSd |
 | N/A | 43FF4C | 436331 | MAI_Path |
@@ -1273,13 +1276,16 @@
 | N/A | N/A | 43AE90 | j_mpqapi_cpp_init |
 | N/A | N/A | 43AE95 | mpqapi_cpp_init |
 | N/A | 4452F2 | 43AEA0 | mpqapi_set_hidden |
+| N/A | N/A | N/A | mpqapi_is_save_modified |
 | N/A | 44532E | 43AEDC | mpqapi_store_creation_time |
 | N/A | 4453A1 | 43AF4F | mpqapi_reg_load_modification_time |
 | N/A | 4453F7 | 43AFA5 | mpqapi_xor_buf |
+| N/A | N/A | N/A | mpqapi_time_before |
+| N/A | N/A | N/A | mpqapi_update_multi_creation_time |
 | N/A | 445416 | 43AFC4 | mpqapi_reg_store_modification_time |
 | N/A | 44544F | 43AFFD | j_mpqapi_remove_hash_entry |
 | 41F97C | 445454 | 43B002 | mpqapi_remove_hash_entry |
-| 41FA0A | 4454A6 | 43B054 | mpqapi_alloc_block |
+| 41FA0A | 4454A6 | 43B054 | mpqapi_free_block |
 | 41FB63 | 445536 | 43B0E4 | mpqapi_new_block |
 | 41FC16 | 445575 | 43B123 | mpqapi_get_hash_index_of_path |
 | 41FC5E | 4455A5 | 43B153 | mpqapi_get_hash_index |
@@ -1793,8 +1799,8 @@
 | 46BFB5 | 458642 | 44B83C | InitPlayer |
 | 46CBAC | 458A42 | 44BB33 | InitMultiView |
 | 46CC04 | 458A7E | 44BB6D | InitPlayerLoc |
-| 46CEDF | N/A | N/A | player_46CEDF |
-| 46CF61 | N/A | N/A | player_46CF61 |
+| 46CEDF | N/A | N/A | PlrGetDir |
+| 46CF61 | N/A | N/A | PlrGetDirXY |
 | 46D035 | 458BDB | 44BCC2 | SolidLoc |
 | 46D06F | 458BEF | 44BCEB | PlrDirOK |
 | 46D1F1 | 458CB0 | 44BD9A | PlrClrTrans |
@@ -1880,7 +1886,7 @@
 | 41BE55 | 45F12F | 450E8E | InitPlrMsg |
 | 41BE80 | 45F14B | 450EAA | DrawPlrMsg |
 | 41BF81 | 45F1D8 | 450F37 | PrintPlrMsg |
-| Beta | Hellfire | Diablo | PORTALS.CPP |
+| Beta | Hellfire | Diablo | PORTAL.CPP |
 | 493F10 | 45F29F | 450FFE | InitPortals |
 | 493F62 | 45F2C5 | 451024 | SetPortalStats |
 | 493FCE | 45F303 | 451062 | AddWarpMissile |
@@ -2267,7 +2273,7 @@
 | N/A | 4798A2 | 462FCC | ReadWaveSection |
 | N/A | 4798FD | 463023 | LoadWaveFile |
 | N/A | 479935 | 46305B | j_mem_free_dbg |
-| Beta | Hellfire | Diablo | WORLD.CPP |
+| Beta | Hellfire | Diablo | RENDER.CPP |
 | 4A048C | 460C68 | 463060 | drawTopArchesUpperScreen |
 | 4A1AB9 | 462295 | 46468D | drawBottomArchesUpperScreen |
 | 4A26F1 | 462ECD | 4652C5 | drawUpperScreen |
```

**Pull request merged**
